# Stage 1: build the app

FROM registry.access.redhat.com/ubi8/nodejs-14 as build
WORKDIR /src/build-your-own-radar
COPY package.json ./

RUN npm install

COPY . ./

ENTRYPOINT []
CMD ["echo", "good morning!"]
# FROM registry.access.redhat.com/ubi8/nginx-120
# 
# COPY --from=build . ./

# Override parent node image's entrypoint script (/usr/local/bin/docker-entrypoint.sh),
# which tries to run CMD as a node command
# ENTRYPOINT []
# CMD ["./build_and_start_nginx.sh"]
# 

