# Stage 1: build the app
FROM registry.access.redhat.com/ubi8/nodejs-16 AS builder
WORKDIR /opt/app-root/src
COPY package.json /opt/app-root/src
USER root
RUN yum update -y 
RUN chown -R 1001:0 "/opt/app-root/src/.npm"
RUN npm -v && npm install -g

COPY . /opt/app-root/src
# RUN npm run build

# FROM registry.access.redhat.com/ubi8/nginx-120
# COPY --from=build /opt/app-root/src/dist/* .

USER 1001
EXPOSE 8080

CMD ["/bin/bash",  "-c",  "sleep infinity"]

